# vim:fileencoding=utf-8:foldmethod=marker

font_family      RecMonoCasual Nerd Font
font_size 14.0
scrollback_lines 200000
show_hyperlink_targets yes
copy_on_select yes
strip_trailing_spaces smart

initial_window_width  1024
initial_window_height 800

tab_activity_symbol ~

background_opacity 0.95
macos_titlebar_color background

background #282828
foreground #ebdbb2
selection_background #d4be98
selection_foreground #1d2021
cursor #ebdbb2
cursor_text_color background
active_tab_background #1d2021
active_tab_foreground #d4be98
active_tab_font_style bold
inactive_tab_background #1d2021
inactive_tab_foreground #a89984
inactive_tab_font_style normal
color0 #665c54
color8 #928374
color1 #ea6962
color9 #ea6962
color2 #a9b665
color10 #a9b665
color3 #e78a4e
color11 #d8a657
color4 #7daea3
color12 #7daea3
color5 #d3869b
color13 #d3869b
color6 #89b482
color14 #89b482
color7 #d4be98
color15 #d4be98


shell /opt/homebrew/bin/fish -l


map shift+cmd+w no_op
map ctrl+shift+k clear_terminal to_cursor active
