theme = "gruvbox_icehess"

[editor]
cursorline = true
cursorcolumn = false
bufferline = "always"
true-color = true
undercurl = true
text-width = 100

[editor.soft-wrap]
enable = false
# max-wrap = 25 # increase value to reduce forced mid-word wrapping
# max-indent-retain = 0
# wrap-indicator = ""  # set wrap-indicator to "" to hide it

[editor.cursor-shape]
insert = "bar"

# [editor.whitespace.render]
# # space = "all"
# # nbsp = "all"
# # tab = "all"
# newline = "all"

[editor.indent-guides]
render = false
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
# skip-levels = 1

[editor.file-picker]
# hidden = false
parents = false
ignore = false
git-ignore = false
git-global = false
git-exclude = false

[editor.statusline]
left = ["mode", "spinner", "file-name", "version-control", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "file-type", "position-percentage", "position", "file-encoding"]
separator = "┊"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
display-inlay-hints = false

[keys.insert]
A-b = ["move_prev_word_start", "move_char_left"]
A-f = ["move_next_word_end", "move_char_right"]
C-b = "move_char_left"
C-d = "delete_char_forward"
C-f = "move_char_right"

[keys.normal]
"\\" = { "\\" = "buffer_picker" }
# "*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection",  "make_search_word_bounded", "search_next"]
# "#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "make_search_word_bounded", "search_prev"]

[keys.normal.space]
F = "file_picker_in_current_buffer_directory"
c = ":buffer-close"
# g = ":pipe-to wizyterm cli split-pane -- helix-live-rg"

[keys.normal.space.t]
s = ":toggle soft-wrap.enable"

[keys.normal.space.m]
f = ":pipe prettier --parser markdown --print-width 120 --prose-wrap preserve"
p = ":pipe prettier --parser markdown --print-width 120 --prose-wrap always"
