[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]
# for vale use vale-ls

[language-server.harper-ls.config.harper-ls]
diagnosticSeverity = "warning"

[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
# config = { typescript = { tsdk = "~/.local/share/nvim/mason/packages/astro-language-server/node_modules/typescript/lib" }, "environment" = "node" }
config = { typescript = { tsdk = "node_modules/typescript/lib" }, "environment" = "node" }

[language-server.ltex-ls-plus.config]
ltex.diagnosticSeverity = "warning"
ltex.disabledRules = { "en-US" = ["PROFANITY"], "en-GB" = ["PROFANITY"] }
ltex.dictionary = { "en-US" = ["builtin"], "en-GB" = ["builtin"] }

[[language]]
name = "astro"
scope = "source.astro"
injection-regex = "astro"
file-types = ["astro"]
language-servers = ["astro-ls"]
roots = ["package.json", "astro.config.mjs"]
formatter = { command = "prettier", args = ["--plugin", "prettier-plugin-astro", "--parser", "astro"] }
auto-format = true


[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "ltex-ls-plus" ]
soft-wrap.enable = false

[[language]]
name = "erlang"
language-servers = [ "erlang-ls" ]

# [language-server.elp]
# command = "elp"
# args = ["--log-file", "~/elp.log", "--no-log-buffering", "server"]

# [language-server.erlang-ls]
# command = "erlang_ls"
# args = ["--log-level", "debug"]

[[language]]
name = "markdown"
language-servers = [ "marksman", "ltex-ls-plus" ]
soft-wrap.enable = false
formatter = { command = 'prettier', args = [
  "--parser",
  "markdown",
  "--prose-wrap",
  "preserve", # <always|never|preserve>
] }
auto-format = false
