[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]
# for vale use vale-ls

[language-server.harper-ls.config.harper-ls]
diagnosticSeverity = "warning"

[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
# config = { typescript = { tsdk = "~/.local/share/nvim/mason/packages/astro-language-server/node_modules/typescript/lib" }, "environment" = "node" }
config = { typescript = { tsdk = "node_modules/typescript/lib" }, "environment" = "node" }

[[language]]
name = "astro"
scope = "source.astro"
injection-regex = "astro"
file-types = ["astro"]
language-servers = ["astro-ls"]
roots = ["package.json", "astro.config.mjs"]
formatter = { command = "prettier", args = ["--plugin", "prettier-plugin-astro", "--parser", "astro"] }
auto-format = true


[[language]]
name = "html"
language-servers = [ "vscode-html-language-server" ]

[[language]]
name = "erlang"
language-servers = [ "erlang-ls" ]


[[language]]
name = "markdown"
language-servers = [ "marksman" ]
# [language-server.elp]
# command = "elp"
# args = ["server"]

# [[language]]
# name = "erlang"
# scope = "source.erlang"
# injection-regex = "erl(ang)?"
# file-types = ["erl", "hrl", "app", "app.src", "erl.src", "escript", { glob = "rebar.config" }, { glob = "rebar.lock" }, { glob = "*.app.src" }]
# roots = ["rebar.config"]
# shebangs = ["escript"]
# comment-token = "%%"
# indent = { tab-width = 4, unit = "    " }
# language-servers = [ "elp" ]
