[tools]
erlang = "27.3.4.15"
node = "lts"
rebar = "latest"
rust = {
  version = "stable",
  profile = "default",
  components = "rust-src"
}

[settings]
idiomatic_version_file_enable_tools = ["node"]

[settings.erlang]
compile = true
